# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=10000)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='MachineContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=10000)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='WebContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=10000)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
